### ISSUE TITLE
One-line all output

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-feed#182]
The output is great currently in that it is pretty compressed and spartan. Though some formatting is slipping through in the final output, causing a number of carriage returns and tab characters to squeak through.

Removing these characters will help reduce size of the feed and simplify processing needed by importers such as the XML importer for WordPress, which [chokes a bit currently](https://wordpress.org/support/topic/this-plugin-is-a-godsend-3/) when it sees these invisible characters.

**Comment by pathawks** [comment]
We are already stripping whitespace from our template. We have been a bit more aggressive in the past, but this has led to problems.

Gzip makes this kind of a moot point anyway. We simply cannot risk breaking any users feeds just to try to shave a few bytes off the feed size.

**Comment by jhabdas** [comment]
No problem, Pat. The perf optimization was more icing on the cake. But if one-lining the output is risky it's definitely not worth it as robust readers/importers should account for `\n` and `\t` characters. And TBH it's kind of nice visually to have the structure while working in my editor.

**Comment by pathawks** [comment]
I would guess that most of the whitespace you are seeing comes from inside the `<content>`? We really don't want to monkey with anything in there, because the user might be relying on something like `<pre>` where whitespace matters.

Trust me, I understand your motivation here. I am a perfectionist and it bothers me if a file is one byte larger than it really needs to be.
