### ISSUE TITLE
Feed-Generator doesn't generate etags

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [jekyll/jekyll-feed#215]
I tried the feed http://blog.jabref.org/feed.xml . The data comming back tells me that __jekyll__ (3.6.2) was the generator of that feed. But the feed doesn't contain an etag.

There is only an `updated` attribute which is a fallback but not a solution. A modern feed should offer an `etag`.

I am not sure where the etag comes from. I used python library `feedparser` which comes back with a complex data structure holding this informations. I don't think that `etag` is part of the HTTP-protocol. This is definitly RSS/Atom-specific. Please see what `feedparser` itself write about `etag`: https://pythonhosted.org/feedparser/http-etag.html

(postet before in "wrong" project: https://github.com/jekyll/jekyll/issues/6866)

**Comment by pathawks** [comment]
Hi @buhtz, sorry you are having this trouble.

`ETag` is an HTTP header, not an element of the feed: 

> The basic concept is that a feed publisher may provide a special HTTP header, called an ETag, when it publishes a feed.

Since Jekyll only generates files—but does not actually serve them—there isn’t any way that we can provide an `ETag`, or any other HTTP header. Instead, your server would have to hash the content of the feed and provide this as an `ETag` header. Many servers provide this functionality, but this is outside the scope of Jekyll or this plugin.

**Comment by buhtz** [comment]
Interesting. In case of that feed how do I know the used server? The feedparser only overs my a `Generator` information.
