### ISSUE TITLE
Limit RSS feed entries

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-feed#40]
Sicking Jekyll Feed loose on my personal site, with 100+ posts, resulted in a 1.1MB file, which is a bit silly for a feed... it shouldn't be an export of the entire site's content.

The go to design would be to add `rss_limit` or similar to your `_config.yml` file, defaulting to something like `10`. That feels lame to me. Why would someone want 11? 25? 5? Feels like we're abstracting a variable for the sense of not hard-coding a number, but I don't see why the number can't be hard-coded. 

What's a good number of posts for a feed? The 10 most recent? 5 most recent? Let's figure out that magic number and just run with it, rather than pushing the question onto users.

**Comment by pathawks** [comment]
Flipboard [requires at least 30 items.](https://about.flipboard.com/rss-spec/)

Keep in mind that feeds are usually downloaded in the background, rather than HTML where the user is just waiting for the page to finish loading. Also, gzip helps a bunch with a big repetitive text file like this.

One problem with hard coding a number that is too low is sites that publish many stories a day. If a reader doesn't pull the feed for a couple days, the reader should still expect to get all the items on the next request. It would be a shame if a site published more items in a few days than the feed contained.

**Comment by benbalter** [comment]
Valid point. On the flip side, FeedBurner (if anyone still uses that), [limits feed to 512kb](https://support.google.com/feedburner/answer/79009?hl=en) (how I discovered the issue).

> ## Is there a feed file size limit?
>
> Yes. FeedBurner will not accept feeds that are larger than 512K. It's rare for a feed to be larger than 512K, but some publishing tools generate their original source feeds with no limit to how far back in time they will reach to include items. Such feeds are vulnerable to steady size increases.
>
>If you currently publish an existing FeedBurner feed, and the original source feed exceeds the 512K limit, FeedBurner will not update the 'burned' version of your feed until the original drops below the limit. For most feeds this will never be an issue -- but if you know that your content postings are regularly very large in size, you might want to keep any eye on the original feed's file size.

**Comment by benbalter** [comment]
As another datapoint, WordPress (which is the top results for "RSS Feed Limit") is [slated to remove the option from WordPress 4.3](https://core.trac.wordpress.org/ticket/32396). From their analysis, less than 1% of users of WordPress.com changed it from the default of 10.

**Comment by pathawks** [comment]
That is certainly a strong datapoint, but keep in mind that, while they are removing this setting from the user-facing dashboard, they are keeping the API so that the setting can still be changed by adding one line of code to a plugin or theme.

Just because, here are just a few others:

 * [GitHub Blog](https://github.com/blog.atom) - 15
 * [New York Times homepage](http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml) - 20
 * [Daring Fireball](http://daringfireball.net/feeds/main) - 47(!)

Certainly 10 would be a reasonable default if it were possible for a user to override, but if the setting is set in stone for all users I worry about setting it too low.

**Comment by XhmikosR** [comment]
Can't the limit be configurable?
