### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-feed#5]
What are the goals of a Jekyll Feed plugin?

Will this produce a feed that takes advantage of every feature that RSS/Atom have to offer, or will it produce a minimum viable feed so that subscribers can be notified of new posts?

Will the plugin try to work around every possible YAML setup to extract things like date / author information, or will this plugin require sites to follow a specific format for front matter?

Will the plugin try to include image thumbnails? Geotag metadata? Podcast enclosures?

Will the plugin offer any sort of "hooks" for others to inject this sort of data?

**Comment by benbalter** [comment]
Great questions, which I purposely left out of the readme as I was hoping for help answering that. Going to speak to my own vision here, but hoping others can weigh in as well.

At minimum, it should be "A Jekyll plugin to generate an (RSS/ATOM) feed for your Jekyll posts", meaning if I add the plugin to my config file, I should get a standards-compliant feed of my most recent posts. The use case I had in mind, is what I'd argue to be the 80% (or 90%+) use case, of "I'd like to allow others to subscribe to my blog in their feed reader". 

There's a lot that it can do, but there's also a lot that it shouldn't. It shouldn't require users to have an intimate understanding of XML standards, or the latests trends in blog publishing to make an educated decision around which option to use (e.g., Atom versus RSS, lets pick one or do both). It also shouldn't look like an airplane cockpit where there's not clear advantage to making something configurable (e.g., the feed containing all posts versus 100 versus 10 versus 11). 

I could see it helping users on the front end, by adding a quick `{{ feed_meta }}` tag, or similar, again, to make it easy for a blogger to have the best possible feed. The reason this all started, was realizing that Jekyll users were solving the same problem over and over again, and not always the best way.

As for wizbang features like thumbnails, geotags, podcasts, hooks, or authors, I'd (A) want to get something out the door and in the hands of publishers as quickly as possible (a `0.1.0`), and (B) would suggest we look at the 80%+ use case, rather than individual users' needs.

**Comment by pathawks** [comment]
I can get behind that. I think if the install process could be as simple as "Add this plugin to your Gemfile, and add `{{ feed_meta }}` to the `<head>` of your site" this plugin would be a wonderful thing. Not sure it will ever fit all of my (rather obscure) needs, but I'd love to lend my support where I can.

I like the idea of progressive enhancement: if a post has categories, then we can add categories to the feed. (Otherwise, nothing happens). I think many features could be approached from this angle.

**Comment by djacquel** [comment]
As Jekyll base already contains a `feed.xml` file, I wonder why a plugin to do the same thing ?

**Comment by benbalter** [comment]
> As Jekyll base already contains a feed.xml file, I wonder why a plugin to do the same thing ?

@djacquel great question. Two key reasons in my mind:

1. Not everyone starts with `jekyll new` (in fact, I suspect most don't)

2. Because the template is versioned within the site, there's no easy way to receive upstream updates. What if we find that the default template doesn't properly XML escape a certain field, or if they update the spec from RSS 2.0 to 2.1? With a Gem, that change is automatic.

**Comment by djacquel** [comment]
Ok, get it !
And I guess that will be available in gh-pages as soon as the plugin is production ready.
Good !

**Comment by pathawks** [comment]
Project Goals will surely evolve over time, but I think we're all on the same page for now.
